version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.14.2-jessie-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Tests
          command: 'npm run test-ci'

workflows:
  build_and_test:
    jobs:
      - test
